name: paktaxcalculator_app
description: "PakTaxCalculator - It's accurate, easy to use, and makes sure your business money is always right."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_app_check: ^0.3.1+3
  firebase_database: ^11.1.4
  cloud_firestore: ^5.4.3
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1
  in_app_purchase: ^3.2.0
  carousel_slider: ^5.0.0
  intl: ^0.17.0
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/bg-img.png
    - assets/tax-splash.gif
    - assets/logo.png
    - assets/banner1.jpg
    - assets/banner2.jpg
    - assets/banner3.jpg
    - assets/icon.png
    - assets/user.png
    - assets/start.png
    - assets/more.png
    - assets/menu.png
    - assets/tax.png
    - assets/gain-tax.png
    - assets/services.png
    - assets/google.png
    - assets/apple.png
    - assets/facebook.png
    - assets/fonts/

  fonts:
    - family: Overpass
      fonts:
        - asset: assets/fonts/Overpass-Regular.ttf
        - asset: assets/fonts/Overpass-Bold.ttf
          weight: 700
